# Generated by Django 4.0.5 on 2022-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentezco', models.PositiveIntegerField(choices=[(1, 'ABUELA'), (2, 'ABUELO'), (3, 'MADRE'), (4, 'PADRE'), (5, 'HERMANA'), (6, 'HERMANO'), (7, 'HIJA/O')], verbose_name='Parentezco')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=15, verbose_name='Apellido')),
                ('edad', models.PositiveIntegerField(max_length=3, verbose_name='Edad')),
            ],
        ),
    ]
